---
- name: tf-nifi-playbook.yml
  hosts: localhost
  become: True
  become_user: root
  tasks:
    - name: CA Certificates package
      package:
        name: "{{ packages }}"
        state: latest
      vars:
        packages:
        - ca-certificates
