---
- name: nodes.yml
  hosts: localhost
  become: True
  become_user: root
  tasks:

    - name: set zookeeper connection string
      set_fact:
        zookeeper_nodes: "{{ name_prefix }}-zk1-{{ name_suffix }}.{{ name_prefix }}{{ name_suffix }}.internal:2173,{{ name_prefix }}-zk2-{{ name_suffix }}.{{ name_prefix }}{{ name_suffix }}.internal:2173,{{ name_prefix }}-zk3-{{ name_suffix }}.{{ name_prefix }}{{ name_suffix }}.internal:2173"

    - name: set host in hosts
      lineinfile:
        path: /etc/hosts
        line: "{{ ansible_default_ipv4.address }} {{ ansible_nodename }} {{ ansible_nodename }}.{{ name_prefix }}{{ name_suffix }}.internal"
        state: present

    - name: nifi required packages
      package:
        name: "{{ packages }}"
        state: latest
      vars:
        packages:
        - java-11-openjdk
        - jq
        - python-pip
        - unzip
      retries: 60
      delay: 3
      register: install_packages
      until: install_packages is not failed

    - name: ansible required packages
      pip:
        executable: /usr/bin/pip
        name: "{{ packages }}"
      vars:
        packages:
        - boto
        - boto3
        - botocore

    - name: set route53 record
      route53:
        state: present
        overwrite: yes
        private_zone: yes
        zone: "{{ name_prefix }}{{ name_suffix }}.internal"
        record: "{{ ansible_nodename }}.{{ name_prefix }}{{ name_suffix }}.internal"
        type: A
        ttl: 600
        value:
          - "{{ ansible_default_ipv4.address }}"
        wait: yes
      retries: 30
      delay: 2
      register: route53_record
      until: route53_record is not failed

    - name: awscli via aws instructions
      get_url:
        url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
        dest: /opt/awscli-exe-linux-x86_64.zip
        owner: root
        group: root
        mode: 0640

    - name: unarchive awscli
      unarchive:
        src: /opt/awscli-exe-linux-x86_64.zip
        dest: /opt/
        creates: /opt/aws

    - name: execute awscli installer
      shell: |
        /opt/aws/install
      args:
        creates: /usr/local/bin/aws

    - name: nifi user
      user:
        name: nifi
        comment: Apache NiFi Service Account

    - name: nifi management directories
      file:
        path: "{{ item }}"
        state: directory
        owner: nifi
        group: nifi
        mode: 0750
      with_items:
        - /opt/nifi-certificates
        - /opt/nifi-conf
        - /opt/nifi-downloads

    - name: remove any previous bucket file (for dynamic bucket changes)
      file:
        path: /opt/nifi-conf/bucket
        state: absent

    - name: set bucket in conf
      lineinfile:
        line: "{{ s3_bucket }}"
        path: /opt/nifi-conf/bucket
        owner: nifi
        group: nifi
        mode: 0640
        create: yes

    - name: check nifi downloaded
      stat:
        path: /opt/nifi-downloads/nifi.tar.gz
      register: nifi_downloaded

    - name: check toolkit downloaded
      stat:
        path: /opt/nifi-downloads/nifi-toolkit.tar.gz
      register: toolkit_downloaded

    - name: download nifi from s3 if not downloaded
      aws_s3:
        mode: get
        bucket: "{{ s3_bucket }}"
        object: "/nifi/downloads/{{ item }}"
        dest: "/opt/nifi-downloads/{{ item }}"
      with_items:
        - nifi.tar.gz
      become_user: nifi
      when:
        - nifi_downloaded.stat.exists == false
      retries: 900
      delay: 2
      register: nifi_from_s3
      until: nifi_from_s3 is not failed

    - name: download toolkit from s3 if not downloaded
      aws_s3:
        mode: get
        bucket: "{{ s3_bucket }}"
        object: "/nifi/downloads/{{ item }}"
        dest: "/opt/nifi-downloads/{{ item }}"
      with_items:
        - nifi-toolkit.tar.gz
      become_user: nifi
      when:
        - toolkit_downloaded.stat.exists == false
      retries: 300
      delay: 2
      register: toolkit_from_s3
      until: toolkit_from_s3 is not failed

    - name: check nifi unarchived
      stat:
        path: /opt/nifi-{{ nifi_version }}/README
      register: nifi_unarchived

    - name: unarchive nifi when not unarchived
      unarchive:
        src: /opt/nifi-downloads/nifi.tar.gz
        dest: /opt
        remote_src: yes
        owner: nifi
        group: nifi
      when: nifi_unarchived.stat.exists == false

    - name: recursive chown nifi
      file:
        path: /opt/nifi-{{ nifi_version }}
        state: directory
        recurse: yes
        owner: nifi
        group: nifi

    - name: link nifi version to /opt/nifi
      file:
        src: /opt/nifi-{{ nifi_version }}
        path: /opt/nifi
        state: link
        mode: 0755
        owner: nifi
        group: nifi

    - name: check toolkit unarchived
      stat:
        path: /opt/nifi-toolkit-{{ nifi_version }}/README
      register: toolkit_unarchived

    - name: unarchive toolkit when not unarchived
      unarchive:
        src: /opt/nifi-downloads/nifi-toolkit.tar.gz
        dest: /opt
        remote_src: yes
        owner: nifi
        group: nifi
      when: toolkit_unarchived.stat.exists == false

    - name: recursive chown toolkit
      file:
        path: /opt/nifi-toolkit-{{ nifi_version }}
        state: directory
        recurse: yes
        owner: nifi
        group: nifi

    - name: link toolkit version to /opt/nifi-toolkit
      file:
        src: /opt/nifi-toolkit-{{ nifi_version }}
        path: /opt/nifi-toolkit
        state: link
        mode: 0755
        owner: nifi
        group: nifi

    - name: authorizers.xml
      template:
        src: authorizers.xml
        dest: /opt/nifi/conf/authorizers.xml
        owner: nifi
        group: nifi
        mode: 0640

    - name: nifi systemd service file
      copy:
        src: nifi.service
        dest: /etc/systemd/system/nifi.service
        mode: 0444
        owner: nifi
        group: nifi

    - name: pull generated password from s3
      aws_s3:
        mode: get
        bucket: "{{ s3_bucket }}"
        object: "/nifi/conf/{{ item }}"
        dest: "/opt/nifi-conf/{{ item }}"
      with_items:
        - generated_password
      become_user: nifi
      retries: 900
      delay: 2
      register: pw_from_s3
      until: pw_from_s3

    - name: set generated_password var
      shell: |
        cat /opt/nifi-conf/generated_password
      become_user: nifi
      register: generated_password

    - name: nifi properties
      template:
        src: nifi.properties
        dest: /opt/nifi/conf/nifi.properties
        owner: nifi
        group: nifi
        mode: 0640

    - name: connect string in state-management
      lineinfile:
        path: /opt/nifi/conf/state-management.xml
        regexp: '        <property name="Connect String">.*</property>'
        line: '        <property name="Connect String">{{ name_prefix }}-zk1-{{ name_suffix }}.{{ name_prefix }}{{ name_suffix }}.internal:2173,{{ name_prefix }}-zk2-{{ name_suffix }}.{{ name_prefix }}{{ name_suffix }}.internal:2173,{{ name_prefix }}-zk3-{{ name_suffix }}.{{ name_prefix }}{{ name_suffix }}.internal:2173</property>'

    - name: check ca exists
      stat:
        path: /opt/nifi-certificates/nifi-cert.pem
      register: ca_cert

    - name: pull ca from s3
      aws_s3:
        mode: get
        bucket: "{{ s3_bucket }}"
        object: "nifi/certificates/{{ item }}"
        dest: "/opt/nifi-certificates/{{ item }}"
      with_items:
        - nifi-cert.pem
        - nifi-key.key
      become_user: nifi
      when: ca_cert.stat.exists == false
      retries: 900
      delay: 2
      register: ca_from_s3
      until: ca_from_s3 is not failed

    - name: check admin exists
      stat:
        path: /opt/nifi-certificates/admin/keystore.p12
      register: admin_cert

    - name: ensure admin dir for s3 objects
      file:
        path: /opt/nifi-certificates/admin
        state: directory
        owner: nifi
        group: nifi
        mode: 0750

    - name: pull admin from s3
      aws_s3:
        mode: get
        bucket: "{{ s3_bucket }}"
        object: "nifi/certificates/admin/{{ item }}"
        dest: "/opt/nifi-certificates/admin/{{ item }}"
      with_items:
        - keystore.p12
        - truststore.jks
      when: admin_cert.stat.exists == false
      become_user: nifi
      retries: 900
      delay: 2
      register: admin_from_s3
      until: admin_from_s3 is not failed

    - name: admin cli.properties template
      template:
        src: cli.properties
        dest: /opt/nifi-certificates/admin/cli.properties
        owner: nifi
        group: nifi
        mode: 0640

    - name: check node keystore exists
      stat:
        path: /opt/nifi-certificates/{{ ansible_nodename }}.{{ name_prefix }}{{ name_suffix }}.internal/keystore.jks
      register: node_cert

    - name: generate node keystore when not exists
      shell: |
        export JAVA_HOME=/etc/alternatives/jre
        /opt/nifi-toolkit/bin/tls-toolkit.sh standalone -n {{ ansible_nodename }}.{{ name_prefix }}{{ name_suffix }}.internal -d 3650 -k 2048 -s SHA256WITHRSA -T jks --subjectAlternativeNames {{ ansible_nodename }},{{ ansible_nodename }}.{{ name_prefix }}{{ name_suffix }}.internal -P {{ generated_password.stdout }} -S {{ generated_password.stdout }}
      args:
        chdir: /opt/nifi-certificates/
        executable: /bin/bash
      become_user: nifi
      when: node_cert.stat.exists == false

    - name: create user
      shell: |
        export JAVA_HOME=/etc/alternatives/jre
        /opt/nifi-toolkit/bin/cli.sh nifi create-user --userName "CN={{ ansible_nodename }}, OU=NIFI" -p /opt/nifi-certificates/admin/cli.properties
      become_user: nifi
      ignore_errors: true

    - name: copy scale-down and scale-up scripts
      template:
        src: "scale-{{ item }}"
        dest: "/usr/local/bin/scale-{{ item }}"
        owner: nifi
        group: nifi
        mode: 0550
      with_items:
        - down
        - up

    - name: timers and service units
      copy:
        src: "{{ item }}"
        dest: "/etc/systemd/system/{{ item }}"
        owner: root
        group: root
        mode: 0640
      with_items:
        - nifi.service
        - nifi.timer

    - name: nifi systemd
      systemd:
        name: "nifi.{{ item }}"
        daemon_reload: yes
        state: started
        enabled: yes
      with_items:
        - service
        - timer

    - name: wait for web port
      wait_for:
        host: "{{ ansible_default_ipv4.address }}"
        port: "{{ web_port }}"
        timeout: 600

    - name: run scale-up script
      shell: |
        /usr/local/bin/scale-up
      become_user: nifi
