---
- name: nodes.yml
  hosts: localhost
  become: True
  become_user: root
  tasks:

    - name: set zookeeper connection string
      set_fact:
        zookeeper_nodes: 'tf-nifi-1:2181,tf-nifi-2:2181,tf-nifi-3:2181'

    - name: set zookeeper ips in /etc/hosts
      lineinfile:
        line: "{{ item }}"
        path: /etc/hosts
      with_items:
        - "# zookeepers"
        - "{{ node1_ip }} tf-nifi-1"
        - "{{ node2_ip }} tf-nifi-2"
        - "{{ node3_ip }} tf-nifi-3"

    - name: nifi required packages
      package:
        name: "{{ packages }}"
        state: latest
      vars:
        packages:
        - default-jre
        - jq
        - openssl
        - nfs-common
        - git
        - binutils
        - python3-pip

    - name: ansible required packages
      pip:
        executable: /usr/bin/pip
        name: "{{ packages }}"
      vars:
        packages:
        - boto
        - boto3
        - botocore

    - name: nifi management directories
      file:
        path: "{{ item }}"
        state: directory
        owner: root
        group: root
        mode: 0750
      with_items:
        - /opt/nifi-certificates
        - /opt/nifi-certificates/admin
        - /opt/nifi-certificates/nifi-ca
        - /opt/nifi-certificates/nifi-node
        - /opt/nifi-certificates/nifi-node/{{ ansible_nodename }}
        - /opt/nifi-conf
        - /opt/nifi-downloads
        - /opt/nifi-cluster
        - /opt/nifi-cluster/join
        - /opt/nifi-cluster/invite
        - /opt/nifi-cluster/leave

    - name: remove any previous bucket file (for dynamic bucket changes)
      file:
        path: /opt/nifi-conf/bucket
        state: absent

    - name: set bucket in conf
      lineinfile:
        line: "{{ s3_bucket }}"
        path: /opt/nifi-conf/bucket
        owner: root
        group: root
        mode: 0640
        create: yes

    - name: certificate directory
      file:
        path: /opt/nifi-certificates/{{ ansible_nodename }}
        state: directory
        owner: root
        group: root
        mode: 0750

    - name: check nifi downloaded
      stat:
        path: /opt/nifi-downloads/nifi.tar.gz
      register: nifi_downloaded

    - name: check toolkit downloaded
      stat:
        path: /opt/nifi-downloads/nifi-toolkit.tar.gz
      register: toolkit_downloaded

    - name: download nifi from s3 if not downloaded
      aws_s3:
        mode: get
        bucket: "{{ s3_bucket }}"
        object: "/nifi/downloads/{{ item }}"
        dest: "/opt/nifi-downloads/{{ item }}"
      with_items:
        - nifi.tar.gz
      when:
        - nifi_downloaded.stat.exists == false
      retries: 60
      delay: 10

    - name: download toolkit from s3 if not downloaded
      aws_s3:
        mode: get
        bucket: "{{ s3_bucket }}"
        object: "/nifi/downloads/{{ item }}"
        dest: "/opt/nifi-downloads/{{ item }}"
      with_items:
        - nifi-toolkit.tar.gz
      when:
        - toolkit_downloaded.stat.exists == false
      retries: 60
      delay: 10

    - name: check nifi unarchived
      stat:
        path: /opt/nifi-{{ nifi_version }}/README
      register: nifi_unarchived

    - name: unarchive nifi when not unarchived
      unarchive:
        src: /opt/nifi-downloads/nifi.tar.gz
        dest: /opt
        remote_src: yes
      when: nifi_unarchived.stat.exists == false

    - name: link nifi version to /opt/nifi
      file:
        src: /opt/nifi-{{ nifi_version }}
        path: /opt/nifi
        state: link
        mode: 0755
        owner: root
        group: root

    - name: check toolkit unarchived
      stat:
        path: /opt/nifi-toolkit-{{ nifi_version }}/README
      register: toolkit_unarchived

    - name: unarchive toolkit when not unarchived
      unarchive:
        src: /opt/nifi-downloads/nifi-toolkit.tar.gz
        dest: /opt
        remote_src: yes
      when: toolkit_unarchived.stat.exists == false

    - name: link toolkit version to /opt/nifi-toolkit
      file:
        src: /opt/nifi-toolkit-{{ nifi_version }}
        path: /opt/nifi-toolkit
        state: link
        mode: 0755
        owner: root
        group: root

    - name: authorizers.xml
      copy:
        src: authorizers.xml
        dest: /opt/nifi/conf/authorizers.xml
        owner: root
        group: root
        mode: 0640

    - name: nifi properties
      template:
        src: nifi.properties
        dest: /opt/nifi/conf/nifi.properties
        owner: root
        group: root
        mode: 0640

    - name: nifi systemd service file
      copy:
        src: nifi.service
        dest: /etc/systemd/system/nifi.service
        mode: 0444
        owner: root
        group: root

    - name: other nodes - pull generated password from s3
      aws_s3:
        mode: get
        bucket: "{{ s3_bucket }}"
        object: "/nifi/conf/{{ item }}"
        dest: "/opt/nifi-conf/{{ item }}"
      with_items:
        - generated_password
      retries: 60
      delay: 10

    - name: set generated_password var
      shell: |
        cat /opt/nifi-conf/generated_password
      register: generated_password

    - name: nodes - wait for toolkit server
      wait_for:
        host: "{{ node1_ip }}"
        port: 2170
        timeout: 360

    - name: get admin files from s3
      aws_s3:
        mode: get
        bucket: "{{ s3_bucket }}"
        object: "/nifi/admin-certificates/{{ item }}"
        dest: "/opt/nifi-certificates/admin/{{ item }}"
      with_items:
        - tls.json
        - keystore.pkcs12
        - cli.properties
      retries: 60
      delay: 10

    - name: check client tls.json
      stat:
        path: /opt/nifi-certificates/nifi-node/{{ ansible_nodename }}/tls.json
      register: node_tls

    - name: toolkit client exec if no tls.json
      shell: |
        export JAVA_HOME=/usr/lib/jvm/default-java
        /opt/nifi-toolkit/bin/tls-toolkit.sh client -a RSA -c tf-nifi-1 -p 2170 -D "CN={{ ansible_nodename }},OU=NIFI" --subjectAlternativeNames {{ ansible_nodename }} -f /opt/nifi-certificates/nifi-node/{{ ansible_nodename }}/tls.json -k 2048 -T jks -t {{ generated_password.stdout }}
      args:
        chdir: /opt/nifi-certificates/nifi-node/{{ ansible_nodename }}
        executable: /bin/bash
      when: node_tls.stat.exists == false

    - name: register KEYSTORE_PASS
      shell: |
        awk -F'"' '/keyStorePassword/ { print $4 }' /opt/nifi-certificates/nifi-node/{{ ansible_nodename }}/tls.json
      register: keystore_pass

    - name: register TRUSTSTORE_PASS
      shell: |
        awk -F'"' '/trustStorePassword/ { print $4 }' /opt/nifi-certificates/nifi-node/{{ ansible_nodename }}/tls.json
      register: truststore_pass

    - name: set keystorePasswd in nifi.properties
      lineinfile:
        path: /opt/nifi/conf/nifi.properties
        regexp: '^nifi\.security\.keystorePasswd=.*'
        line: "nifi.security.keystorePasswd={{ keystore_pass.stdout }}"

    - name: set keyPasswd in nifi.properties
      lineinfile:
        path: /opt/nifi/conf/nifi.properties
        regexp: '^nifi\.security\.keyPasswd=.*'
        line: "nifi.security.keyPasswd={{ keystore_pass.stdout }}"

    - name: set truststorePasswd in nifi.properties
      lineinfile:
        path: /opt/nifi/conf/nifi.properties
        regexp: '^nifi\.security\.truststorePasswd=.*'
        line: "nifi.security.truststorePasswd={{ truststore_pass.stdout }}"

    - name: touch local join
      file:
        path: "/opt/nifi-cluster/join/{{ ansible_nodename }}"
        state: touch
        owner: root
        group: root
        mode: 0640

    - name: copy join to s3
      aws_s3:
        mode: put
        bucket: "{{ s3_bucket }}"
        object: "/nifi/cluster/join/{{ ansible_nodename }}"
        src: "/opt/nifi-cluster/join/{{ ansible_nodename }}"

    - name: get invite to s3
      aws_s3:
        mode: get
        bucket: "{{ s3_bucket }}"
        object: "/nifi/cluster/invite/{{ ansible_nodename }}"
        dest: "/opt/nifi-cluster/invite/{{ ansible_nodename }}"
      retries: 60
      delay: 10     

    - name: remove invite in s3
      aws_s3:
        mode: delobj
        bucket: "{{ s3_bucket }}"
        object: "/nifi/cluster/invite/{{ ansible_nodename }}"

    - name: get nifi conf files from s3
      aws_s3:
        mode: get
        bucket: "{{ s3_bucket }}"
        object: "/nifi/conf/{{ item }}"
        dest: "/opt/nifi/conf/{{ item }}"
      with_items:
        - users.xml
        - authorizations.xml
        - flow.xml.gz
      retries: 60
      delay: 10

    - name: copy scale-down script executed by autoscaling ssm doc
      copy:
        src: scale-down
        dest: /usr/local/bin/scale-down
        owner: root
        group: root
        mode: 0550

    - name: nifi systemd service start/enable
      systemd:
        state: started
        enabled: yes
        name: nifi
        daemon_reload: yes
