---
- name: nifi-leave.yml
  hosts: localhost
  become: True
  become_user: root
  gather_facts: false
  tasks:

    - name: determine lock
      stat:
        path: /mnt/nifi/cluster/lock-leave
      register: cluster_lock

    - name: end if cluster lock
      meta: end_host
      when:
        - cluster_lock.stat.exists == true

    - name: find cluster leave
      find:
        paths: /mnt/nifi/cluster/leave
        patterns: '*'
      register: cluster_leave

    - name: end if no files match
      meta: end_host
      when:
        - cluster_leave.matched == 0

    - name: set lock
      file:
        path: /mnt/nifi/cluster/lock-leave
        state: directory
        owner: root
        group: root
        mode: 0640
      register: set_lock

    - name: process leaves by deleting from cluster
      shell: |
        /opt/nifi-toolkit/bin/cli.sh nifi delete-node --nifiNodeId {{ item.path | basename }} -p /mnt/nifi/admin-certificates/cli.properties
      with_items: "{{ cluster_leave.files }}"
      when: set_lock.changed
      ignore_errors: True

    - name: remove lock
      file:
        path: /mnt/nifi/cluster/lock-leave
        state: absent
      when: set_lock.changed

    - name: check node no longer in cluster and remove from leave queue
      shell: |
        /opt/nifi-toolkit/bin/cli.sh nifi get-nodes -p /mnt/nifi/admin-certificates/cli.properties | grep --quiet {{ item }}
        if [ $? -eq 0 ]
          then rm /mnt/nifi/cluster/leave/{{ item }}
        fi
      with_items: "{{ cluster_leave.files }}"
