---
- name: nifi-leave.yml
  hosts: localhost
  become: True
  become_user: root
  gather_facts: false
  tasks:

    - name: get bucket name
      shell: |
        cat /opt/nifi-conf/bucket
      register: s3_bucket

    - name: determine lock exists
      aws_s3:
        mode: list
        bucket: "{{ s3_bucket.stdout }}"
        object: "/nifi/cluster/{{ item }}"
      with_items:
        - lock-leave
      ignore_errors: true
      register: lock_leave

    - name: end if lock-leave found
      meta: end_host
      when:
        - lock_leave | length != 0

    - name: get leave requests
      aws_s3:
        mode: list
        bucket: "{{ s3_bucket.stdout }}"
        object: "/nifi/cluster/leave/"
      ignore_errors: true
      register: cluster_leave

    - name: end if no leave keys other than virtual directory prefix
      meta: end_host
      when:
        - cluster_leave | length <= 1

    - name: touch local leave lock
      file:
        state: touch
        path: /opt/nifi-cluster/lock-leave
        owner: root
        group: root
        mode: '0640'

    - name: set lock
      aws_s3:
        mode: put
        bucket: "{{ s3_bucket.stdout }}"
        object: "/nifi/cluster/lock-leave"
        src: "{{ item }}"
      with_items:
        - /opt/nifi-cluster/lock-leave

    - name: process leaves by deleting from cluster
      shell: |
        /opt/nifi-toolkit/bin/cli.sh nifi delete-node --nifiNodeId {{ item.path | basename }} -p /mnt/nifi/admin-certificates/cli.properties
      with_items: 
        - "{{ cluster_leave.s3_keys | reject('eq','nifi/cluster/leave/') | list }}"
      ignore_errors: True

    - name: remove leave request(s)
      aws_s3:
        mode: delobj
        bucket: "{{ s3_bucket.stdout }}"
        object: "{{ item }}"
      with_items:
        - "{{ cluster_leave.s3_keys }}"

    - name: remove lock
      aws_s3:
        mode: delobj
        bucket: "{{ s3_bucket.stdout }}"
        object: "/nifi/cluster/lock-leave"
